#!/usr/bin/env python3
"""
Transcribe audio from a meeting video to a timestamped .txt file.
Uses moviepy to extract audio and openai-whisper for transcription.
"""

import re
import sys
from pathlib import Path
from typing import List

# Source video (path from project's compress_video.py)
VIDEO_PATH = Path(
    "/Users/myhomefolder/Downloads/Hardware_AWG/Meeting materials/2025-08-28/"
    "Hardware AWG meeting - 2025_08_28 07_50 PDT - Recording.mp4"
)
PROJECT_DIR = Path(__file__).resolve().parent
OUTPUT_TXT = PROJECT_DIR / "meeting_transcript_improved.txt"
TEMP_AUDIO = PROJECT_DIR / "_temp_meeting_audio.wav"

# Whisper model: "tiny", "base", "small", "medium", "large" (larger = better quality, slower)
WHISPER_MODEL = "small"

# Post-processing: fix known misrecognitions and normalize acronyms
REPLACEMENTS = [
    (r"\bTechCort\b", "TechCore"),
    (r"\btechcort\b", "TechCore"),
    (r"\bcell drop\b", "celldrop"),
    (r"\bCell drop\b", "celldrop"),
    (r"\bcell drop fluids\b", "celldrop fluids"),  # after "cell drop" so order matters
    (r"\bOSDR\b", "OSDR"),  # ensure capitalized (no-op if already)
    (r"\bosdr\b", "OSDR"),
    (r"\bOsdr\b", "OSDR"),
    (r"\bALSDA\b", "ALSDA"),
    (r"\balsda\b", "ALSDA"),
    (r"\bAlsda\b", "ALSDA"),
    (r"\bPSI\b", "PSI"),
    (r"\bpsi\b", "PSI"),
    (r"\bPsi\b", "PSI"),
    (r"\bBPS\b", "BPS"),
    (r"\bbps\b", "BPS"),
    (r"\bBps\b", "BPS"),
    (r"Aaron [Pp]rasad\b", "Aaron Persaud"),
    (r"Aaron [Pp]ersaud\b", "Aaron Persaud"),
]
CORRECTION_PATTERNS = [(re.compile(p), r) for p, r in REPLACEMENTS]


def apply_corrections(text: str) -> str:
    """Apply known corrections for names, product names, and acronyms."""
    for pattern, replacement in CORRECTION_PATTERNS:
        text = pattern.sub(replacement, text)
    return text


def sec_to_timestamp(seconds: float) -> str:
    """Convert seconds to HH:MM:SS.mmm."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}"


def extract_audio_moviepy(video_path: Path, audio_path: Path) -> None:
    """Extract audio from video to WAV using moviepy."""
    from moviepy import VideoFileClip

    print("Extracting audio with moviepy...")
    clip = VideoFileClip(str(video_path))
    clip.audio.write_audiofile(str(audio_path))
    clip.close()


def transcribe_with_whisper(audio_path: Path) -> List[dict]:
    """Transcribe audio with openai-whisper; return list of segments with start, end, text."""
    import whisper

    print(f"Loading Whisper model '{WHISPER_MODEL}'...")
    model = whisper.load_model(WHISPER_MODEL)
    print("Transcribing...")
    result = model.transcribe(str(audio_path), fp16=False)
    return result.get("segments", [])


def write_timestamped_transcript(segments: List[dict], out_path: Path) -> None:
    """Write transcript with timestamps to a text file."""
    lines = [
        "Meeting transcript (with timestamps, improved model + corrections)",
        "Source: " + str(VIDEO_PATH),
        "Generated by transcribe_meeting.py (Whisper small, post-corrections)",
        "",
        "---",
        "",
    ]
    for seg in segments:
        start = seg.get("start", 0)
        end = seg.get("end", 0)
        text = (seg.get("text") or "").strip()
        if not text:
            continue
        text = apply_corrections(text)
        ts_range = f"[{sec_to_timestamp(start)} - {sec_to_timestamp(end)}]"
        lines.append(f"{ts_range} {text}")
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Transcript written to {out_path}")


def main() -> int:
    if not VIDEO_PATH.exists():
        print(f"Video not found: {VIDEO_PATH}", file=sys.stderr)
        return 1

    PROJECT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        extract_audio_moviepy(VIDEO_PATH, TEMP_AUDIO)
        segments = transcribe_with_whisper(TEMP_AUDIO)
        write_timestamped_transcript(segments, OUTPUT_TXT)
        return 0
    finally:
        if TEMP_AUDIO.exists():
            TEMP_AUDIO.unlink()
            print("Removed temporary audio file.")


if __name__ == "__main__":
    sys.exit(main())
